################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.c \
../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.o \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_conv_q7.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_q7.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q15.d \
./arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/%.o: ../arm/CMSIS_5/CMSIS/DSP/Source/FilteringFunctions/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m33 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Werror -Wall  -g3 -Ddg_configDEVICE=DA14699_00 -DARM_MATH_ARMV8MML -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\middleware\adapters\include" -I"C:\BLE_SDK10_examples\features\Voice_recognition\include" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\bsp\util\include" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\bsp\memory\include" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\bsp\config" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\middleware\config" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\bsp\include" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\free_rtos\include" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\free_rtos\portable\GCC\DA1469x" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\middleware\osal" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\bsp\system\sys_man\include" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\bsp\peripherals\include" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\bsp\snc\include" -I"C:\0_my_Dialog\NeuralNetworks\DA14695\SDK_10.0.10.118\sdk\bsp\snc\src" -I"C:\BLE_SDK10_examples\features\Voice_recognition\tensorflow" -I"C:\BLE_SDK10_examples\features\Voice_recognition\tensorflow\third_party" -I"C:\BLE_SDK10_examples\features\Voice_recognition\tensorflow\third_party\gemmlowp" -I"C:\BLE_SDK10_examples\features\Voice_recognition\arm" -I"C:\BLE_SDK10_examples\features\Voice_recognition\arm\CMSIS_5\CMSIS\Core\Include" -I"C:\BLE_SDK10_examples\features\Voice_recognition\arm\CMSIS_5\CMSIS\DSP\PrivateInclude" -I"C:\BLE_SDK10_examples\features\Voice_recognition\arm\CMSIS_5\CMSIS\DSP\Include" -I"C:\BLE_SDK10_examples\features\Voice_recognition\arm\CMSIS_5\CMSIS\NN\Include" -include"C:\BLE_SDK10_examples\features\Voice_recognition\config\custom_config_ram.h" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


